### ISSUE TITLE
SimBrief integration - pirep prefile

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#405]
* Refactor the JS calls to use JSON responses for vars
* Move SB calls into `SimBriefService` class
* Create a prefiled PIREP with the OFP info

#### Table

Separate `simbrief_ofp` table

```yaml
simbrief:
  id: ofp id
  user_id: string (required)
  flight_id: string #nullable
  pirep_id: string # nullable
  ofp_html: string (html)
  ofp_xml:
  created_at: 
  updated_at: 
```
